/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conectar.conexion;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonatan Lara
 */
public class Search extends javax.swing.JPanel {

    private DefaultTableModel modelo;
    public Search() {
        initComponents();
        model();
        verficicacionID(txtbusqueda);
        Consulta();
    }
    public void model(){
        String columnas[]={"Matricula","Nombre","Programa","Estatus"};
        String filas[][]={};
        modelo = new DefaultTableModel(filas, columnas);
        tabla.setModel(modelo);
    }
    public void verficicacionID(final JTextField textField){
        textField.addKeyListener(new KeyAdapter() {
             public void keyTyped(KeyEvent e){
                 int limite= 8;
                 char caracter = e.getKeyChar();
            
                 if (Character.isLetter(caracter)) {//solo letras isDigit(caracter)
                        getToolkit().beep();
                        e.consume();//no me deja escribir
                }
             }
        });
    }
    private void Consulta() {
        conexion con =  new conexion();
        con.conectar();
        String info="";
        Object Datos[];
        try {
            
            ResultSet r = con.getStatement().executeQuery("select * from alumnos");
            r.beforeFirst();
            while (r.next()) {                
                
                Datos = new Object[4];
                Datos[0]=r.getString("matricula");
                Datos[1]=r.getString("nombre");
                Datos[2]=r.getString("programa");
                Datos[3]=r.getString("estatus");
                modelo.addRow(Datos);
            }
            ///JOptionPane.showMessageDialog(null, info);
           
        } catch (Exception e) {
             System.out.println(""+e);
        }
    }
    public void busqueda(){
        String sql="Select * from alumnos WHERE matricula LIKE ?";
        Object Datos[];
        conexion con =  new conexion();
        Connection reg = con.getConnection();
        try {
        
           PreparedStatement pst = reg.prepareStatement(sql);
           pst.setString(1, txtbusqueda.getText() +"%");
           ResultSet r = pst.executeQuery();
            r.beforeFirst();
            
            while (r.next()) {                
                
                Datos = new Object[4];
                Datos[0]=r.getString("matricula");
                Datos[1]=r.getString("nombre");
                Datos[2]=r.getString("programa");
                Datos[3]=r.getString("estatus");
                modelo.addRow(Datos);
            }
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        txtbusqueda.setToolTipText("Ingresa el ID");
        txtbusqueda.setBorder(null);
        txtbusqueda.setOpaque(false);
        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyTyped(evt);
            }
        });

        tabla.setBackground(new java.awt.Color(204, 204, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buscar.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/barraBuscar.png"))); // NOI18N

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(130, 130, 130)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 271, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtbusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyTyped
       busqueda();
    }//GEN-LAST:event_txtbusquedaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtbusqueda;
    // End of variables declaration//GEN-END:variables
}
